# Generated by Django 4.2.13 on 2025-11-21 13:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vacation_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='message',
        ),
        migrations.AddField(
            model_name='notification',
            name='request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vacation_app.vacationrequest'),
        ),
        migrations.AddField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('request_approved', 'Request Approved'), ('request_rejected', 'Request Rejected'), ('request_created', 'Request Created'), ('reminder_upcoming', 'Upcoming Vacation Reminder')], default='request_created', max_length=50),
        ),
    ]
