# Generated by Django 4.2.13 on 2025-11-27 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacation_app', '0002_vacationrequest_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('request_approved', 'Request Approved'), ('request_rejected', 'Request Rejected'), ('request_created', 'Request Created'), ('reminder_upcoming', 'Upcoming Vacation Reminder'), ('request_rescheduled', 'Request Rescheduled')], default='request_created', max_length=50),
        ),
    ]
